import { CSSProperties } from "react";
import Background from "./_components/background";
import { Navbar } from "./_components/navbar";
import "./globals.css";
import { Inter, JetBrains_Mono } from "next/font/google";

const sansFont = Inter({ subsets: ["latin"] });
const monoFont = JetBrains_Mono({ subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-900 text-white antialiased" style={{
      "--font-mono": monoFont.style.fontFamily
    } as CSSProperties}>
      <body className={sansFont.className}>
        <Navbar />
        <Background>
          <main className="relative">{children}</main>
        </Background>
      </body>
    </html>
  );
}
